### ISSUE TITLE
インストールと実行の手順を書く

### ISSUE THREAD

**Issue by dannyso16** [jphacks/D_2016#26]

**Comment by feynfeyn888** [comment]
トラブルシューティング
### 権限の問題
  1. 管理者権限でPowerShellを開く
  2. 以下のコマンドを打ち込む
  ```
  $ Set-ExecutionPolicy RemoteSigned
  ```
  3. 以下のようなレスが返ってくるので、```RemoteSigned```を打ち込む.
  
  ```
  コマンド パイプライン位置 1 のコマンドレット Set-ExecutionPolicy
  次のパラメーターに値を指定してください:
  ExecutionPolicy:
  ```
参照:[実行ポリシーについて](https://docs.microsoft.com/ja-jp/powershell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-7)

### 文字エンコードの問題(UTF-8では動かないがJISなら動いた)
こちらについては対応済みなので大丈夫。

**Comment by dannyso16** [comment]
one driveが挟まるとエラーが出る
→one driveをパスに挟まないようにすると治る

**Comment by dannyso16** [comment]
0908640b1e307c36decb9df216785224e64f18af
