### ISSUE TITLE
texttospeech/gtts.py のエラーについて

### ISSUE THREAD

**Issue by dannyso16** [jphacks/D_2016#9]
`texttospeech/gtts.py`を実行すると
`ImportError: cannot import name 'gTTS' from partially initialized module 'gtts' (most likely due to a circular import) `と出ます。

これは、`from gtts import gTTS`の部分の`gtts`が
- pipで導入したものと
- 自分自身のファイル名と
で循環参照になるから見たいです。

ファイル名を変えると治るはずです。

**Comment by feynfeyn888** [comment]
チェックしていただきありがとうございます！
